### ISSUE TITLE
Usage of Symfony CMF

### ISSUE THREAD

**Issue by RyanMcEvoy** [Symplify/ModularRouting#2]
I've just begun using this bundle and noticed that the composer configuration includes Symfony CMF Routing Bundle yet does not use it.

It would be good to have it removed from the dependency list if it is not actually required.

**Comment by RyanMcEvoy** [comment]
I retract this comment, I have since realised that Symfony CMF is a requirement as this service injects into it.

I really need to stop drinking so much coffee...

**Comment by TomasVotruba** [comment]
Hey @RyanMcEvoy 

Thanks for spotting anyway. It would be better not to depend on Symfony CMF, yet it would require creating own chain router mechanism. If you like, you can send PR for that.
